-   id: prettier
    name: prettier
    description: ''
    entry: src/gproducts/pse-results/node_modules/.bin/prettier --write --list-different --ignore-unknown
    language: node
    'types': [text]
    args: []
    require_serial: false
    minimum_pre_commit_version: '0'
    files: src/gproducts/pse-results
    types_or: [css,html,javascript,json,jsx,ts,tsx]

